export const products = [
  { id: 1, name: "Apple", quantity: 50, brand: "FreshFarms", price: 0.5 },
  {
    id: 2,
    name: "Banana",
    quantity: 100,
    brand: "TropicalDelight",
    price: 0.3,
  },
  { id: 3, name: "Orange Juice", quantity: 25, brand: "CitrusJoy", price: 2.5 },
  { id: 4, name: "Milk", quantity: 40, brand: "DairyPure", price: 1.2 },
  { id: 5, name: "Bread", quantity: 30, brand: "Baker'sChoice", price: 1.5 },
  { id: 6, name: "Eggs (Dozen)", quantity: 20, brand: "HappyHens", price: 2.0 },
  { id: 7, name: "Butter", quantity: 15, brand: "CreamyGold", price: 3.0 },
  {
    id: 8,
    name: "Rice (1kg)",
    quantity: 60,
    brand: "GrainHarvest",
    price: 1.8,
  },
  { id: 9, name: "Pasta", quantity: 80, brand: "ItalianEssence", price: 1.0 },
  {
    id: 10,
    name: "Tomato Sauce",
    quantity: 50,
    brand: "SaucyGoodness",
    price: 1.3,
  },
  { id: 11, name: "Cheese", quantity: 25, brand: "CheddarHouse", price: 4.5 },
  {
    id: 12,
    name: "Chicken Breast",
    quantity: 30,
    brand: "FarmFresh",
    price: 5.0,
  },
  {
    id: 13,
    name: "Carrot (1kg)",
    quantity: 70,
    brand: "VeggieGreen",
    price: 0.9,
  },
  {
    id: 14,
    name: "Potatoes (1kg)",
    quantity: 90,
    brand: "EarthHarvest",
    price: 0.7,
  },
  { id: 15, name: "Yogurt", quantity: 35, brand: "ProbioticKing", price: 1.2 },
];
